"""Merges autogenerated citation network with hand made annotations and edits. Annotated version has priority.

Usage:
    merge_annotations.py <ANNOTATED_FILE> <GENERATED_FILE>

Arguments:
    ANNOTATED_FILE      json file edited by hand
    GENERATED_FILE      json file generated automatically
"""

from docopt import docopt
import json


if __name__ == "__main__":
    args = docopt(__doc__)
    annot_file = args['<ANNOTATED_FILE>']
    gen_file = args['<GENERATED_FILE>']

    with open(annot_file) as infile:
        annotations = json.load(infile)
    with open(gen_file) as infile:
        citations = json.load(infile)

    for key in citations.keys():
        if key in annotations:
            for cited_key in citations[key].keys():
                if cited_key not in annotations[key]:
                    annotations[key][cited_key] = ""
        else:
            annotations[key] = citations[key]

    print json.dumps(annotations, indent=2, sort_keys=True)

    
